# -*- coding: utf-8 -*-
"""N最终blur_yolov11_BoT_SORT_ReID_person_id_blur_overlay_export.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19cu934WtdDrW8KOuMyNnw_eOyg0qgsfH

# 🎥 CCTV Space Tracker — YOLOv11 + BoT-SORT + ReID

**Simplified output version**

This version keeps the workflow simple:

1. Set manual session metadata
2. Run YOLOv11 + BoT-SORT + ReID once
3. Label/merge the full-run track IDs into person IDs
4. Export only the files you actually need:
   - one raw annotated detection/tracking video
   - one final CSV with `person_id`
   - one reference frame image
   - one privacy-preserving video with blurred bounding boxes and final `person_id` overlay

**Important time logic:** this notebook does not read the upper-left video overlay and does not use video metadata or runtime file-creation time. It uses manual date/time first; if manual start time is empty, it can use the full datetime from the filename as backup.

---

## Cell 1 — Install dependencies
"""

!pip install -q ultralytics lap ipywidgets openpyxl
from IPython.display import display
import ipywidgets as widgets
print('✅ Dependencies ready')

"""## Cell 2 — Mount Google Drive"""

from google.colab import drive
drive.mount('/content/drive')
print('✅ Drive mounted')

"""## Cell 3 — ⚙️ Configuration

Edit this cell for each video.

**Time rule:**

1. If `START_TIME_MANUAL` has a value, the notebook uses `DATE + START_TIME_MANUAL`.
2. If `START_TIME_MANUAL = ""`, the notebook tries to read the full timestamp from the filename, e.g. `20260214083552` → `2026-02-14 08:35:52`.
3. If the filename has no timestamp, it falls back to `DATE + 00:00:00`.

**No OCR:** it does not read the upper-left timestamp printed inside the video image.

**No runtime metadata:** it does not use video creation time, upload time, or notebook run time.

---

"""

import os
from pathlib import Path

VIDEO_PATH  = "/content/drive/MyDrive/CCTV/CCTV_C1/Atrium1_20260227_N.mp4"
OUTPUT_DIR  = "/content/drive/MyDrive/CCTV/CCTV_C1/Atrium1_20260227_N"
os.makedirs(OUTPUT_DIR, exist_ok=True)

# -------------------------------------------------------------------
# Manual session metadata
# -------------------------------------------------------------------
# Manual date used when START_TIME_MANUAL is provided, or when filename backup is unavailable.
DATE              = "2026-02-27"       # YYYY-MM-DD
DAY               = 1                  # study day number, e.g. 1–14
SESSION           = "Noon 12–14"    # session label
CAMERA_ID         = "C1"               # camera label, e.g. C1–C7

# The notebook uses this as frame-0 wall-clock time.
# If you leave it empty "", it will try the filename timestamp as backup.
START_TIME_MANUAL = "12:00:00"

# Filename backup only applies when START_TIME_MANUAL = "".
# It uses the FULL filename datetime, not only the time.
# Example filename: Atrium_NEW_lunares_zew_20260214083552_20260214083924_624667.mp4
USE_FILENAME_DATETIME_BACKUP = True

YOLO_MODEL  = "yolo11m.pt"      # yolo11n.pt = faster; yolo11m.pt = better quality
CONF_THRES  = 0.25
VID_STRIDE  = 300                # process 1 frame every N frames
SAVE_VIDEO  = True              # write annotated tracking video

# Final CSV contains only real labelled people.
# Noise / Skip / UNLABELLED are removed from the final CSV.
EXCLUDE_NOISE_FROM_FINAL = True

PARTICIPANT_IDS = [
    "AA-01", "AA-02", "AA-03", "AA-04", "AA-05", "AA-06", "AA-07",
    "Visitor", "Noise", "Skip"
]

STEM         = Path(VIDEO_PATH).stem
VIS_VIDEO    = os.path.join(OUTPUT_DIR, f"{STEM}_detection_video.mp4")
PERSON_ID_BLUR_VIDEO = os.path.join(OUTPUT_DIR, f"{STEM}_person_id_blur_overlay.mp4")
FINAL_CSV    = os.path.join(OUTPUT_DIR, f"{STEM}_final_person_id.csv")
REF_FRAME    = os.path.join(OUTPUT_DIR, f"{STEM}_reference_frame.jpg")
TRACKER_YAML = "/content/botsort_reid.yaml"

print(f"Video      : {VIDEO_PATH}")
print(f"Output     : {OUTPUT_DIR}")
print(f"Model      : {YOLO_MODEL}")
print(f"Manual date: {DATE}")
print(f"Start time : {START_TIME_MANUAL if START_TIME_MANUAL else 'filename backup if available'}")
print(f"Outputs    :")
print(f"  1) detection video → {VIS_VIDEO}")
print(f"  2) final person_id CSV → {FINAL_CSV}")
print(f"  3) frame image     → {REF_FRAME}")
print(f"  4) blurred person_id video → {PERSON_ID_BLUR_VIDEO}")

"""## Cell 4 — Write BoT-SORT + ReID tracker config"""

TRACKER_CFG = """\
tracker_type: botsort
track_high_thresh: 0.25
track_low_thresh: 0.10
new_track_thresh: 0.35
track_buffer: 180
match_thresh: 0.85
fuse_score: True
gmc_method: sparseOptFlow
proximity_thresh: 0.4
appearance_thresh: 0.7
with_reid: True
model: yolo11m-cls.pt
"""

with open(TRACKER_YAML, "w") as f:
    f.write(TRACKER_CFG)

print(f"✅ Tracker config written → {TRACKER_YAML}")

"""## Cell 5 — 🎞️ Load model, read video info, and set recording time

This version does **not** use upper-left OCR and does **not** use video metadata / runtime creation time.

For frame timestamps, the notebook uses:

1. `DATE + START_TIME_MANUAL`, if `START_TIME_MANUAL` is not empty
2. full filename timestamp backup, only if `START_TIME_MANUAL = ""`
3. `DATE + 00:00:00`, if both are unavailable

The exported `date` column is derived from the actual `recording_start` used above, so if filename backup is used, the date also comes from the filename.

---

"""

import cv2
import re
from pathlib import Path
from datetime import datetime, timedelta
from ultralytics import YOLO

model = YOLO(YOLO_MODEL)

cap = cv2.VideoCapture(VIDEO_PATH)
FPS = cap.get(cv2.CAP_PROP_FPS) or 25.0
TOTAL = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
W = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
H = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
cap.release()

def _parse_filename_timestamp(video_path):
    """
    Look for a CCTV-style 14-digit timestamp in the filename:
    YYYYMMDDHHMMSS, for example 20260214083552.

    Returns the FULL datetime from filename, not only the time.
    """
    stem = Path(video_path).stem
    candidates = re.findall(r"(20\d{12})", stem)
    for ts in candidates:
        try:
            return datetime.strptime(ts, "%Y%m%d%H%M%S"), f"filename timestamp {ts}"
        except Exception:
            pass
    return None, "no filename timestamp"

def infer_recording_start(video_path, manual_date, manual_start_time):
    """
    Recording start logic:
    1. If START_TIME_MANUAL is provided, use DATE + START_TIME_MANUAL.
    2. If START_TIME_MANUAL is empty, use the FULL datetime from filename as backup.
    3. If filename has no timestamp, use DATE + 00:00:00.

    This function never uses OCR, video metadata, file creation time, or notebook runtime.
    """
    manual_date = str(manual_date).strip()
    manual_start_time = str(manual_start_time).strip()

    if manual_start_time:
        return datetime.strptime(f"{manual_date} {manual_start_time}", "%Y-%m-%d %H:%M:%S"), "manual DATE + START_TIME_MANUAL"

    if USE_FILENAME_DATETIME_BACKUP:
        file_dt, source = _parse_filename_timestamp(video_path)
        if file_dt is not None:
            return file_dt, source + " full datetime backup"

    return datetime.strptime(f"{manual_date} 00:00:00", "%Y-%m-%d %H:%M:%S"), "manual DATE + default 00:00:00"

recording_start, TIME_SOURCE = infer_recording_start(VIDEO_PATH, DATE, START_TIME_MANUAL)

DATE_EXPORT = recording_start.strftime("%Y-%m-%d")
START_TIME_USED = recording_start.strftime("%H:%M:%S")
ANALYSIS_FPS = FPS / VID_STRIDE
FRAME_INTERVAL = VID_STRIDE / FPS

print(f"Video: {TOTAL} frames | {FPS:.2f} fps | {TOTAL/FPS:.1f}s | {W}×{H}")
print(f"Analysis stride: {VID_STRIDE} → effective {ANALYSIS_FPS:.2f} fps")
print(f"Recording start used for datetime: {recording_start} ← {TIME_SOURCE}")
print(f"Exported date column: {DATE_EXPORT} ← derived from recording_start")
print(f"Start time used: {START_TIME_USED}")

"""## Cell 6 — 🚀 Full tracking run once

This runs YOLO/BoT-SORT once and saves only the annotated detection video as a file.  
Raw detections stay in memory as `df_raw` for the labelling step, so the output folder does not get filled with raw/audit/summary files.

"""

import pandas as pd
import numpy as np
import time
import math
from tqdm.auto import tqdm

print(f"Video: {TOTAL} frames | {FPS:.2f} fps | {TOTAL/FPS:.1f}s")
print(f"Analysis: stride={VID_STRIDE} → effective {ANALYSIS_FPS:.2f} fps")
print(f"Model: {YOLO_MODEL} | Tracker: BoT-SORT + ReID")
print("Running full tracking pass once...\n")

# How many frames will actually be processed by YOLO
TOTAL_PROCESSED = math.ceil(TOTAL / VID_STRIDE)

print(f"Total original frames: {TOTAL:,}")
print(f"Frames to process after stride: {TOTAL_PROCESSED:,}")
print(f"Estimated analysis duration: {TOTAL_PROCESSED / ANALYSIS_FPS:.1f}s in output video time\n")

writer = None
if SAVE_VIDEO:
    writer = cv2.VideoWriter(
        VIS_VIDEO,
        cv2.VideoWriter_fourcc(*"mp4v"),
        ANALYSIS_FPS,
        (W, H)
    )

raw_rows = []
proc_idx = 0
raw_track_thumbs = {}

def format_seconds(seconds):
    """Convert seconds to hh:mm:ss format."""
    seconds = int(max(0, seconds))
    h = seconds // 3600
    m = (seconds % 3600) // 60
    s = seconds % 60
    if h > 0:
        return f"{h:02d}:{m:02d}:{s:02d}"
    return f"{m:02d}:{s:02d}"


def update_track_thumbnail(tid, conf, frame_bgr, frame_idx, x1, y1, x2, y2):
    pad = 10
    x1c = max(0, int(x1) - pad)
    y1c = max(0, int(y1) - pad)
    x2c = min(W, int(x2) + pad)
    y2c = min(H, int(y2) + pad)

    crop_bgr = frame_bgr[y1c:y2c, x1c:x2c]
    if crop_bgr.size == 0:
        return

    crop_rgb = cv2.cvtColor(crop_bgr, cv2.COLOR_BGR2RGB)

    th = 128
    tw = max(1, int(crop_rgb.shape[1] * th / max(1, crop_rgb.shape[0])))
    crop_thumb = cv2.resize(crop_rgb, (tw, th))

    if tid not in raw_track_thumbs:
        raw_track_thumbs[tid] = {
            "crop": crop_thumb,
            "frame": frame_idx,
            "count": 1,
            "conf": float(conf),
        }
    else:
        raw_track_thumbs[tid]["count"] += 1

        # Keep the clearest thumbnail, based on highest confidence
        if float(conf) > raw_track_thumbs[tid]["conf"]:
            raw_track_thumbs[tid]["crop"] = crop_thumb
            raw_track_thumbs[tid]["frame"] = frame_idx
            raw_track_thumbs[tid]["conf"] = float(conf)


start_time_run = time.time()
last_update_time = start_time_run

pbar = tqdm(
    total=TOTAL_PROCESSED,
    desc="Full tracking",
    unit="processed frame",
    dynamic_ncols=True,
)

try:
    for result in model.track(
        source=VIDEO_PATH,
        tracker=TRACKER_YAML,
        persist=True,
        stream=True,
        classes=[0],
        conf=CONF_THRES,
        vid_stride=VID_STRIDE,
        verbose=False,
    ):
        # First processed frame is frame 0
        orig_frame_idx = proc_idx * VID_STRIDE
        proc_idx += 1

        video_t = orig_frame_idx / FPS
        dt = recording_start + timedelta(seconds=video_t)
        ts_str = dt.strftime("%Y-%m-%d %H:%M:%S")
        time_of_day = dt.strftime("%H:%M:%S")

        if SAVE_VIDEO and writer is not None:
            writer.write(result.plot())

        frame_bgr = result.orig_img

        # Count detections in this processed frame
        detections_this_frame = 0

        if result.boxes is not None and len(result.boxes) > 0:
            for box in result.boxes:
                if box.id is None:
                    continue

                tid = int(box.id[0])
                conf = float(box.conf[0])
                x1, y1, x2, y2 = box.xyxy[0].tolist()

                cx = (x1 + x2) / 2
                cy = (y1 + y2) / 2

                update_track_thumbnail(
                    tid, conf, frame_bgr, orig_frame_idx, x1, y1, x2, y2
                )

                raw_rows.append({
                    "frame": orig_frame_idx,
                    "processed_frame": proc_idx,
                    "datetime": ts_str,
                    "time_of_day": time_of_day,
                    "time_sec": round(video_t, 2),
                    "date": DATE_EXPORT,
                    "day": DAY,
                    "session": SESSION,
                    "camera": CAMERA_ID,
                    "time_source": TIME_SOURCE,
                    "track_id": tid,
                    "x1": round(x1, 2),
                    "y1": round(y1, 2),
                    "x2": round(x2, 2),
                    "y2": round(y2, 2),
                    "cx": round(cx, 2),
                    "cy": round(cy, 2),
                    "cx_norm": round(cx / W, 4),
                    "cy_norm": round(cy / H, 4),
                    "confidence": round(conf, 3),
                })

                detections_this_frame += 1

        # Progress and ETA
        elapsed = time.time() - start_time_run
        processed = proc_idx
        avg_sec_per_processed_frame = elapsed / max(processed, 1)
        remaining = max(TOTAL_PROCESSED - processed, 0)
        eta = remaining * avg_sec_per_processed_frame

        # Update tqdm display
        pbar.update(1)

        # Avoid refreshing too aggressively
        now = time.time()
        if now - last_update_time > 1.0 or processed == TOTAL_PROCESSED:
            pbar.set_postfix({
                "orig_frame": f"{orig_frame_idx:,}",
                "elapsed": format_seconds(elapsed),
                "ETA": format_seconds(eta),
                "sec/frame": f"{avg_sec_per_processed_frame:.2f}",
                "detections": f"{len(raw_rows):,}",
                "tracks": len(raw_track_thumbs),
            })
            last_update_time = now

finally:
    pbar.close()

    if SAVE_VIDEO and writer is not None:
        writer.release()
        print(f"✅ Detection video saved → {VIS_VIDEO}")


total_elapsed = time.time() - start_time_run

print("\n✅ Full tracking finished.")
print(f"Runtime: {format_seconds(total_elapsed)}")
print(f"Processed frames: {proc_idx:,} / expected {TOTAL_PROCESSED:,}")
print(f"Average speed: {proc_idx / max(total_elapsed, 1):.2f} processed frames/sec")
print(f"Average time: {total_elapsed / max(proc_idx, 1):.2f} sec/processed frame")

df_raw = pd.DataFrame(raw_rows)

if len(df_raw) == 0:
    print("⚠️ No person detections found. Check VIDEO_PATH, model, CONF_THRES, and video visibility.")
else:
    summary = (
        df_raw.groupby("track_id")
        .agg(
            detections=("track_id", "size"),
            first_frame=("frame", "min"),
            last_frame=("frame", "max"),
            first_time=("datetime", "min"),
            last_time=("datetime", "max"),
            mean_confidence=("confidence", "mean"),
            max_confidence=("confidence", "max"),
        )
        .reset_index()
        .sort_values(["detections", "max_confidence"], ascending=False)
    )

    print(f"\nTotal detections: {len(df_raw):,}")
    print(f"Unique full-run raw tracks: {df_raw['track_id'].nunique()}")

    display(summary.head(20))

"""## Cell 7 — 🏷️ Post-run interactive label UI

Label the actual full-run track IDs into `person_id`. Multiple raw `track_id`s can be assigned to the same `person_id`.

Default is `Noise`. `Noise`, `Skip`, and `UNLABELLED` are removed from the final CSV.

"""

import pandas as pd
import cv2
import io
import base64
import ipywidgets as widgets
from IPython.display import display
from PIL import Image as PILImage

label_map = {}

assert "df_raw" in globals() and len(df_raw) > 0, "df_raw is empty. Run the full tracking cell first."
assert "raw_track_thumbs" in globals() and len(raw_track_thumbs) > 0, "No thumbnails found. Run the full tracking cell first."

def crop_to_b64(arr):
    img = PILImage.fromarray(arr)
    buf = io.BytesIO()
    img.save(buf, format="PNG")
    return base64.b64encode(buf.getvalue()).decode()

track_ids = sorted(df_raw["track_id"].dropna().astype(int).unique())
rows = []

for tid in track_ids:
    info = raw_track_thumbs.get(int(tid))
    if info is None:
        continue
    b64 = crop_to_b64(info["crop"])
    html = widgets.HTML(
        value=f"""
        <div style="width:220px; border:1px solid #ddd; padding:8px; margin:4px">
          <img src="data:image/png;base64,{b64}" style="max-width:200px; max-height:150px"><br>
          <b>raw track_id: {tid}</b><br>
          detections: {info["count"]}<br>
          best conf: {info["conf"]:.2f}<br>
          best frame: {info["frame"]}
        </div>
        """
    )
    dropdown = widgets.Dropdown(
        options=PARTICIPANT_IDS,
        value="Noise",
        description="person_id:",
        layout=widgets.Layout(width="220px")
    )
    rows.append((tid, dropdown, widgets.VBox([html, dropdown])))

grid = widgets.GridBox(
    [box for _, _, box in rows],
    layout=widgets.Layout(grid_template_columns="repeat(3, 250px)", grid_gap="10px")
)

confirm_btn = widgets.Button(description="Confirm labels", button_style="success")
out = widgets.Output()

def on_confirm(_):
    global label_map
    label_map = {int(tid): dd.value for tid, dd, _ in rows}
    with out:
        out.clear_output()
        print("✅ Labels confirmed.")
        print(label_map)

confirm_btn.on_click(on_confirm)
display(grid, confirm_btn, out)

"""## Cell 8 — 💾 Export final CSV only

This exports exactly one final CSV with `person_id`.

The final CSV excludes `Noise`, `Skip`, and `UNLABELLED` by default. No Excel, no audit CSV, and no extra summary file are written.

Final CSV columns are restricted to:

```python
COL_ORDER = [
    "frame",
    "date", "time_of_day", "datetime", "time_sec",
    "day", "session", "camera",
    "track_id", "person_id",
    "x1", "y1", "x2", "y2", "cx", "cy", "cx_norm", "cy_norm",
    "confidence",
]
```

"""

import pandas as pd

assert label_map, "⚠️ label_map is empty. Run the post-run label UI and click 'Confirm labels' first."
assert "df_raw" in globals() and len(df_raw) > 0, "df_raw is empty. Run the full tracking cell first."

df = df_raw.copy()

# The human-cleaned identity column is called person_id.
# Multiple raw track_id values can be mapped to the same person_id.
df["person_id"] = df["track_id"].map(label_map).fillna("UNLABELLED")

if EXCLUDE_NOISE_FROM_FINAL:
    df_final = df[~df["person_id"].isin(["Noise", "Skip", "UNLABELLED"])].copy()
else:
    df_final = df[df["person_id"] != "Skip"].copy()

# Keep the date consistent with the recording_start actually used.
# Manual DATE + START_TIME_MANUAL is used first; filename datetime is only used when START_TIME_MANUAL is empty.
df_final["date"] = DATE_EXPORT

# Final CSV columns only. No processed_frame, no time_source, no aaid.
COL_ORDER = [
    "frame",
    "date", "time_of_day", "datetime", "time_sec",
    "day", "session", "camera",
    "track_id", "person_id",
    "x1", "y1", "x2", "y2", "cx", "cy", "cx_norm", "cy_norm",
    "confidence",
]

# Ensure the final export follows exactly the requested column order.
df_final = df_final[[c for c in COL_ORDER if c in df_final.columns]]

df_final.to_csv(FINAL_CSV, index=False)

print(f"✅ Final person_id CSV saved → {FINAL_CSV}")
print("-" * 70)
print(f"Raw rows in memory: {len(df):,}")
print(f"Final labelled person_id rows: {len(df_final):,}")
print(f"Removed Noise/Skip/UNLABELLED rows: {len(df) - len(df_final):,}")
print(f"Exported date column: {DATE_EXPORT} ← {TIME_SOURCE}")
print("Final person_ids:", sorted(df_final["person_id"].unique()) if len(df_final) else [])
display(df_final.head(10))

"""## Cell 9 — 🖼️ Save one reference frame"""

# Save one reference frame for spatial calibration / homography.
import cv2

REF_FRAME_IDX = 0   # change this if you want another frame

cap = cv2.VideoCapture(VIDEO_PATH)
cap.set(cv2.CAP_PROP_POS_FRAMES, REF_FRAME_IDX)
ok, frame = cap.read()
cap.release()

if ok:
    cv2.imwrite(REF_FRAME, frame)
    print(f"✅ Reference frame saved → {REF_FRAME}")
else:
    print("⚠️ Could not read reference frame. Check VIDEO_PATH and REF_FRAME_IDX.")

"""## Cell 10 — 🎬 Export blurred video with final `person_id` overlay

This cell creates the privacy-preserving export video after you have confirmed labels and exported `df_final`.

It uses the cleaned `person_id` mapping, not raw `track_id`. Each bounding box region is blurred first, then the final `person_id` label is drawn on top.

"""

import cv2
import pandas as pd
import numpy as np
import math
from tqdm.auto import tqdm
from pathlib import Path

# -------------------------------------------------------------------
# Privacy-preserving person_id video export
# -------------------------------------------------------------------
# Output frame rate follows the analysis video, not the original CCTV fps.
# This keeps the exported video aligned with the frames actually analysed by YOLO.

if "PERSON_ID_BLUR_VIDEO" not in globals():
    PERSON_ID_BLUR_VIDEO = os.path.join(OUTPUT_DIR, f"{Path(VIDEO_PATH).stem}_person_id_blur_overlay.mp4")

# Prefer the in-memory final dataframe. If the runtime was restarted, reload FINAL_CSV.
if "df_final" in globals() and len(df_final) > 0:
    df_video = df_final.copy()
else:
    assert os.path.exists(FINAL_CSV), "FINAL_CSV not found. Run Cell 8 first, or make sure FINAL_CSV points to the exported person_id CSV."
    df_video = pd.read_csv(FINAL_CSV)

required_cols = {"frame", "person_id", "x1", "y1", "x2", "y2"}
missing = required_cols - set(df_video.columns)
assert not missing, f"Missing required columns for video export: {missing}"

# Keep only real labelled people. This prevents Noise / Skip / UNLABELLED from being drawn.
df_video = df_video[~df_video["person_id"].isin(["Noise", "Skip", "UNLABELLED"])].copy()
df_video["frame"] = df_video["frame"].astype(int)

# One analysed frame may contain multiple people.
boxes_by_frame = {
    int(frame): group.to_dict("records")
    for frame, group in df_video.groupby("frame", sort=True)
}
frames_to_export = sorted(boxes_by_frame.keys())

assert len(frames_to_export) > 0, "No labelled person_id boxes available for video export. Check df_final / FINAL_CSV."

# Re-open original video so the blurred export is drawn on the original image, not on the YOLO track_id plot.
cap = cv2.VideoCapture(VIDEO_PATH)
assert cap.isOpened(), f"Could not open VIDEO_PATH: {VIDEO_PATH}"

writer = cv2.VideoWriter(
    PERSON_ID_BLUR_VIDEO,
    cv2.VideoWriter_fourcc(*"mp4v"),
    ANALYSIS_FPS,
    (W, H),
)
assert writer.isOpened(), f"Could not create output video: {PERSON_ID_BLUR_VIDEO}"


def _clip_box(x1, y1, x2, y2, width, height):
    """Clip box coordinates to the image boundary and return integers."""
    x1 = max(0, min(width - 1, int(round(x1))))
    y1 = max(0, min(height - 1, int(round(y1))))
    x2 = max(0, min(width, int(round(x2))))
    y2 = max(0, min(height, int(round(y2))))
    if x2 <= x1 or y2 <= y1:
        return None
    return x1, y1, x2, y2


def _blur_roi(frame, x1, y1, x2, y2, blur_strength=51):
    """Blur only the inside of the bounding box."""
    roi = frame[y1:y2, x1:x2]
    if roi.size == 0:
        return frame

    # Gaussian kernel must be odd and positive.
    k = max(15, int(blur_strength))
    if k % 2 == 0:
        k += 1

    blurred = cv2.GaussianBlur(roi, (k, k), 0)
    frame[y1:y2, x1:x2] = blurred
    return frame


def _draw_person_id_label(frame, label, x1, y1, x2, y2):
    """Draw final person_id label and bounding box. No raw track_id is shown."""
    label = str(label)

    # Bounding box outline
    cv2.rectangle(frame, (x1, y1), (x2, y2), (255, 255, 255), 2)

    font = cv2.FONT_HERSHEY_SIMPLEX
    font_scale = 0.7
    thickness = 2
    (tw, th), baseline = cv2.getTextSize(label, font, font_scale, thickness)

    # Place label above the box if possible, otherwise inside the top of the box.
    pad = 5
    label_x1 = x1
    label_y1 = max(0, y1 - th - baseline - 2 * pad)
    label_x2 = min(frame.shape[1], x1 + tw + 2 * pad)
    label_y2 = min(frame.shape[0], label_y1 + th + baseline + 2 * pad)

    # If the label would be outside the image, move it inside the box.
    if y1 - th - baseline - 2 * pad < 0:
        label_y1 = y1
        label_y2 = min(frame.shape[0], y1 + th + baseline + 2 * pad)

    cv2.rectangle(frame, (label_x1, label_y1), (label_x2, label_y2), (0, 0, 0), -1)
    cv2.putText(
        frame,
        label,
        (label_x1 + pad, label_y2 - baseline - pad),
        font,
        font_scale,
        (255, 255, 255),
        thickness,
        cv2.LINE_AA,
    )
    return frame


written = 0
try:
    for frame_idx in tqdm(frames_to_export, desc="Export blurred person_id video", unit="frame", dynamic_ncols=True):
        cap.set(cv2.CAP_PROP_POS_FRAMES, int(frame_idx))
        ok, frame = cap.read()
        if not ok:
            continue

        # First blur every labelled person box.
        clipped_boxes = []
        for row in boxes_by_frame[frame_idx]:
            clipped = _clip_box(row["x1"], row["y1"], row["x2"], row["y2"], W, H)
            if clipped is None:
                continue
            x1, y1, x2, y2 = clipped
            frame = _blur_roi(frame, x1, y1, x2, y2, blur_strength=51)
            clipped_boxes.append((row["person_id"], x1, y1, x2, y2))

        # Then draw clean person_id overlays on top of the blurred regions.
        for person_id, x1, y1, x2, y2 in clipped_boxes:
            frame = _draw_person_id_label(frame, person_id, x1, y1, x2, y2)

        writer.write(frame)
        written += 1

finally:
    cap.release()
    writer.release()

print("✅ Blurred person_id overlay video exported")
print(f"Output video: {PERSON_ID_BLUR_VIDEO}")
print(f"Frames written: {written:,}")
print(f"Unique person_id labels shown: {sorted(df_video['person_id'].unique())}")
print("Note: the exported video shows final person_id only. Raw track_id is not overlaid.")